export const MOOD_OPTIONS = [
  // 开心
  { emoji: '😊', label: '开心' },
  { emoji: '😄', label: '大笑' },
  { emoji: '😁', label: '得意' },
  { emoji: '😆', label: '搞笑' },
  { emoji: '😂', label: '笑哭' },
  { emoji: '🤣', label: '笑死' },
  { emoji: '😜', label: '调皮' },
  { emoji: '🤪', label: '搞怪' },
  { emoji: '😎', label: '酷' },
  { emoji: '🥳', label: '庆祝' },
  { emoji: '🎉', label: '派对' },

  // 喜欢 / 幸福
  { emoji: '🥰', label: '幸福' },
  { emoji: '😍', label: '喜欢' },
  { emoji: '😘', label: '亲亲' },
  { emoji: '🤩', label: '兴奋' },
  { emoji: '❤️', label: '心动' },
  { emoji: '💕', label: '甜蜜' },
  { emoji: '💗', label: '恋爱' },
  { emoji: '🙏', label: '感恩' },

  // 平静 / 思考
  { emoji: '😌', label: '平静' },
  { emoji: '😇', label: '乖巧' },
  { emoji: '🤔', label: '思考' },
  { emoji: '🤓', label: '专注' },
  { emoji: '😐', label: '一般' },
  { emoji: '😶', label: '无语' },
  { emoji: '🤗', label: '拥抱' },

  // 负面情绪
  { emoji: '😢', label: '难过' },
  { emoji: '😭', label: '大哭' },
  { emoji: '🥺', label: '委屈' },
  { emoji: '😞', label: '失望' },
  { emoji: '😕', label: '困惑' },
  { emoji: '😣', label: '头疼' },
  { emoji: '😫', label: '焦虑' },
  { emoji: '🤯', label: '崩溃' },
  { emoji: '😤', label: '生气' },
  { emoji: '😡', label: '愤怒' },
  { emoji: '😨', label: '害怕' },
  { emoji: '😮', label: '惊讶' },
  { emoji: '😱', label: '震惊' },
  { emoji: '🥱', label: '无聊' },
  { emoji: '😴', label: '疲惫' },
  { emoji: '🤒', label: '生病' },
  { emoji: '🤢', label: '恶心' },
  { emoji: '💔', label: '心碎' },

  // 天气
  { emoji: '☀️', label: '晴天' },
  { emoji: '⛅', label: '多云' },
  { emoji: '🌧️', label: '下雨' },
  { emoji: '⛈️', label: '雷雨' },
  { emoji: '❄️', label: '下雪' },
  { emoji: '🌫️', label: '雾霾' },
  { emoji: '🌈', label: '彩虹' },

  // 饮食
  { emoji: '☕', label: '咖啡' },
  { emoji: '🍵', label: '喝茶' },
  { emoji: '🥤', label: '奶茶' },
  { emoji: '🍜', label: '吃饭' },
  { emoji: '🍔', label: '快餐' },
  { emoji: '🍕', label: '披萨' },
  { emoji: '🍰', label: '甜点' },
  { emoji: '🍺', label: '喝酒' },
  { emoji: '🍻', label: '干杯' },
  { emoji: '🍎', label: '水果' },

  // 工作 / 学习
  { emoji: '💻', label: '加班' },
  { emoji: '💼', label: '工作' },
  { emoji: '📚', label: '学习' },
  { emoji: '✍️', label: '写作' },
  { emoji: '🎨', label: '画画' },
  { emoji: '📷', label: '摄影' },
  { emoji: '🎬', label: '电影' },
  { emoji: '🎧', label: '音乐' },
  { emoji: '🎮', label: '游戏' },
  { emoji: '📺', label: '追剧' },
  { emoji: '💰', label: '赚钱' },
  { emoji: '🧧', label: '红包' },
  { emoji: '🤝', label: '合作' },
  { emoji: '🚗', label: '通勤' },
  { emoji: '✈️', label: '出差' },

  // 生活 / 居家
  { emoji: '🏠', label: '宅家' },
  { emoji: '🛏️', label: '睡觉' },
  { emoji: '🌙', label: '熬夜' },
  { emoji: '🧹', label: '打扫' },
  { emoji: '🛒', label: '购物' },
  { emoji: '🎁', label: '礼物' },
  { emoji: '🎂', label: '生日' },
  { emoji: '💐', label: '鲜花' },
  { emoji: '🌸', label: '赏花' },

  // 运动 / 户外
  { emoji: '🏃', label: '运动' },
  { emoji: '🚶', label: '散步' },
  { emoji: '🚴', label: '骑行' },
  { emoji: '🏊', label: '游泳' },
  { emoji: '⛰️', label: '爬山' },
  { emoji: '🏖️', label: '度假' },
  { emoji: '🌊', label: '大海' },
  { emoji: '🌃', label: '夜景' },
  { emoji: '🧘', label: '冥想' },

  // 其他
  { emoji: '✨', label: '美好' },
  { emoji: '🔥', label: '干劲' },
  { emoji: '💪', label: '加油' },
] as const;
